import { OnboardingQuestion } from "../types/onboarding.types";

export const ONBOARDING_STEPS_COUNT = 11; // 1 Welcome + 9 Questions + 1 Completion

export const ONBOARDING_QUESTIONS: OnboardingQuestion[] = [
  {
    id: "welcome",
    title: "Welcome to StudyMate AI",
    description: "Let's personalize your workspace to fit your studying needs. It only takes a minute.",
    type: "welcome",
    required: true,
  },
  {
    id: "education",
    title: "What are you studying?",
    description: "Select your main academic or professional focus.",
    type: "single",
    field: "education",
    required: true,
    options: [
      { value: "computer_science", label: "Computer Science", icon: "Laptop" },
      { value: "engineering", label: "Engineering", icon: "Cpu" },
      { value: "medical", label: "Medical & Life Sciences", icon: "HeartPulse" },
      { value: "business", label: "Business & Finance", icon: "Coins" },
      { value: "arts", label: "Arts & Humanities", icon: "Palette" },
      { value: "other", label: "Other Focus", icon: "GraduationCap" },
    ],
  },
  {
    id: "subjects",
    title: "Which subjects are you studying right now?",
    description: "Choose all that apply. This helps us customize your study library.",
    type: "multi",
    field: "subjects",
    required: true,
    options: [
      { value: "programming", label: "Programming & Code", icon: "Code" },
      { value: "databases", label: "Database Systems", icon: "Database" },
      { value: "operating_systems", label: "Operating Systems", icon: "Layers" },
      { value: "networks", label: "Computer Networks", icon: "Network" },
      { value: "ai_ml", label: "Artificial Intelligence", icon: "Brain" },
      { value: "calculus", label: "Calculus & Math", icon: "Sigma" },
      { value: "physics", label: "Physics", icon: "Atom" },
      { value: "literature", label: "Literature & Writing", icon: "BookOpen" },
    ],
  },
  {
    id: "goals",
    title: "What would you like StudyMate AI to help you achieve?",
    description: "Pick as many goals as you'd like.",
    type: "multi",
    field: "primaryGoals",
    required: true,
    options: [
      { value: "score_higher", label: "Score Higher on Tests", icon: "TrendingUp" },
      { value: "revise_faster", label: "Revise Faster", icon: "Zap" },
      { value: "understand_concepts", label: "Understand Complex Concepts", icon: "Lightbulb" },
      { value: "stay_organized", label: "Stay Organized", icon: "Calendar" },
      { value: "prepare_exams", label: "Prepare for Upcoming Exams", icon: "FileText" },
      { value: "build_habits", label: "Build Daily Study Habits", icon: "Hourglass" },
    ],
  },
  {
    id: "heard_from",
    title: "How did you hear about us?",
    description: "Help us understand how you found StudyMate AI.",
    type: "single",
    field: "heardFrom",
    required: true,
    options: [
      { value: "youtube", label: "YouTube", icon: "Youtube" },
      { value: "instagram", label: "Instagram", icon: "Instagram" },
      { value: "friend", label: "A Friend or Classmate", icon: "UserPlus" },
      { value: "university", label: "University / School", icon: "Building" },
      { value: "google", label: "Google Search", icon: "Search" },
      { value: "other", label: "Other source", icon: "MoreHorizontal" },
    ],
  },
  {
    id: "interests",
    title: "Which topics interest you outside your studies?",
    description: "This is optional. We use this to generate creative analogies.",
    type: "multi",
    field: "interests",
    required: false, // Skippable
    options: [
      { value: "gaming", label: "Gaming", icon: "Gamepad2" },
      { value: "sports", label: "Sports & Fitness", icon: "Dumbbell" },
      { value: "reading", label: "Reading & Podcasts", icon: "BookOpen" },
      { value: "music", label: "Music & Concerts", icon: "Music" },
      { value: "photography", label: "Photography & Travel", icon: "Camera" },
      { value: "design", label: "Art & Graphic Design", icon: "PenTool" },
      { value: "writing", label: "Creative Writing", icon: "FileEdit" },
      { value: "business_startup", label: "Business & Startups", icon: "Briefcase" },
      { value: "coding_hobby", label: "Side Programming Projects", icon: "Terminal" },
    ],
  },
  {
    id: "learning_style",
    title: "How do you learn best?",
    description: "Choose your favorite learning mediums.",
    type: "multi",
    field: "learningStyles",
    required: true,
    options: [
      { value: "reading_notes", label: "Reading Study Notes", icon: "FileText" },
      { value: "watching_videos", label: "Watching Explanatory Videos", icon: "Play" },
      { value: "practice_questions", label: "Solving Practice Questions", icon: "CheckSquare" },
      { value: "flashcards", label: "Reviewing Flashcards", icon: "Copy" },
      { value: "teaching_others", label: "Explaining/Teaching Others", icon: "Users" },
      { value: "ai_explanations", label: "Conversational AI Explanations", icon: "MessageSquareCode" },
    ],
  },
  {
    id: "study_time",
    title: "How much do you usually study each day?",
    description: "Select a comfortable starting goal. You can adjust this later.",
    type: "single",
    field: "dailyStudyTime",
    required: true,
    options: [
      { value: "30_min", label: "30 minutes", icon: "Clock" },
      { value: "1_hour", label: "1 hour", icon: "Clock" },
      { value: "2_hours", label: "2 hours", icon: "Clock" },
      { value: "4_hours", label: "4 hours", icon: "Clock" },
      { value: "6_plus_hours", label: "6+ hours", icon: "Clock" },
    ],
  },
  {
    id: "next_exam",
    title: "When is your next exam?",
    description: "Optional. We can use this to set up a study countdown.",
    type: "date",
    field: "nextExam",
    required: false, // Skippable
  },
  {
    id: "dashboard_focus",
    title: "What would you like to see first?",
    description: "Select which view you want your home dashboard to focus on.",
    type: "single",
    field: "dashboardFocus",
    required: true,
    options: [
      { value: "chat", label: "AI Chat", icon: "MessageSquare" },
      { value: "library", label: "Study Library", icon: "FolderClosed" },
      { value: "quiz", label: "Quiz Room", icon: "Trophy" },
      { value: "flashcards", label: "Flashcards Studio", icon: "Copy" },
      { value: "planner", label: "Revision Planner", icon: "Calendar" },
    ],
  },
  {
    id: "finish",
    title: "You're all set!",
    description: "We've personalized your workspace based on your profile. Let's start learning.",
    type: "finish",
    required: true,
  },
];
